session_name: g-sup
start_directory: ~/dev/gusto-support
shell_command_before:
  - cd ~/dev/gusto-support
  - nvm use
windows:
  - window_name: code
    panes:
    -
  - window_name: rails s
    panes:
    - shell_command: rs -p 7190
  - window_name: rails c
    panes:
    - shell_command: rc
  - window_name: webpack
    panes:
    - shell_command: bin/webpack-dev-server
  - window_name: test
    panes:
    -
